<a href="https://colab.research.google.com/github/KwonTaekhyun/Python-Practice/blob/main/numpy%2C_pandas_%EA%B8%B0%EC%B4%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# 개요

1. numpy 
2. pandas
3. torch로 vector, matrix 등 만들어보기

## 참고자료
* Official tutorial: https://docs.scipy.org/doc/numpy/reference/
* Stanford Univ. CS231 tutorial: http://cs231n.github.io/python-numpy-tutorial/

## 1. numpy, array, matrix 등

In [1]:
# version 차이로 인한 오류 배제
import warnings
warnings.filterwarnings("ignore")

In [2]:
import numpy as np

### 리스트, 행렬 선언

In [3]:
# list_name(변수명 설정) = ["item-1", "item-2", ... , "item-n"]

a = [1, 2, 3]
b = ["a", "b", "c"]
c = [["a"], ["a", "b"], ["a", "c"], ["a", "b", "c"]]

print(a)
print(b)
print(c)

[1, 2, 3]
['a', 'b', 'c']
[['a'], ['a', 'b'], ['a', 'c'], ['a', 'b', 'c']]


In [4]:
# append()로 리스트에 item 추가하기
c.append('new_item')
c.append(['new_item_list'])

print(c)

[['a'], ['a', 'b'], ['a', 'c'], ['a', 'b', 'c'], 'new_item', ['new_item_list']]


In [5]:
a = np.array([1, 2, 3])
b = np.array(["a", "b", "c"])
c = np.array([["a"], ["a", "b"], ["a", "c"], ["a", "b", "c"]])

print(a)
print(b)
print(c)

[1 2 3]
['a' 'b' 'c']
[list(['a']) list(['a', 'b']) list(['a', 'c']) list(['a', 'b', 'c'])]


In [6]:
# 배열(또는 행렬)을 1로 채우기
print(np.ones((1, 5)))
print(np.ones((3, 2)))

[[1. 1. 1. 1. 1.]]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [7]:
# 배열(또는 행렬)을 0으로 채우기
print(np.zeros((1, 5)))
print(np.zeros((3, 2)))

[[0. 0. 0. 0. 0.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


In [8]:
# 주어진 범위 안에서 순차적으로 증가하는 리스트 만들기
# np.arange([start,] stop, [step,] dtype=None)

print(np.arange(10))
print(np.arange(3,7, dtype=np.float))
print(np.arange(3,10,2))

[0 1 2 3 4 5 6 7 8 9]
[3. 4. 5. 6.]
[3 5 7 9]


In [9]:
# 행렬 선언하기
mat1 = np.array([[1,2,3],[4,5,6]])

# random으로 matrix 만들기
mat2 = np.random.randint(low=1, high=10, size=(3,2))
mat3 = np.random.rand(3,2)

print(mat1)
print(mat2)
print(mat3)

[[1 2 3]
 [4 5 6]]
[[9 8]
 [4 6]
 [5 9]]
[[0.60937374 0.49982028]
 [0.38010238 0.06817112]
 [0.82002729 0.01194238]]


### 리스트 인덱싱(Indexing) & 슬라이싱(Slicing)

In [10]:
# Indexing
a = [1,3,5,7,9,11]
print(a[2], a[5], a[-1])

5 11 11


In [11]:
# Slicing
b = [2,4,6,8,10]
print(b[2:])
print(b[:2])
print(b[:])

[6, 8, 10]
[2, 4]
[2, 4, 6, 8, 10]


### numpy의 reshape (PyTorch의 view와 비교)

In [12]:
# (row, column)
mat1 = np.random.rand(6,3)
print(mat1)

[[0.62717198 0.9767459  0.33733423]
 [0.27199963 0.74917611 0.30619961]
 [0.63100014 0.15593883 0.50771736]
 [0.87758114 0.722176   0.27743593]
 [0.5927205  0.34753994 0.86772023]
 [0.94484466 0.20659625 0.62953443]]


In [15]:
# -1: all
print(mat1.reshape(1, -1).shape)
# 원본 행렬은 변하지 않음
print(mat1)
print(mat1.reshape(1, -1))
# 원본 행렬은 변하지 않음
print(mat1)
print("=====")
print(mat1.reshape(-1, 1).shape)
print(mat1.reshape(-1, 1))

(1, 18)
[[0.62717198 0.9767459  0.33733423]
 [0.27199963 0.74917611 0.30619961]
 [0.63100014 0.15593883 0.50771736]
 [0.87758114 0.722176   0.27743593]
 [0.5927205  0.34753994 0.86772023]
 [0.94484466 0.20659625 0.62953443]]
[[0.62717198 0.9767459  0.33733423 0.27199963 0.74917611 0.30619961
  0.63100014 0.15593883 0.50771736 0.87758114 0.722176   0.27743593
  0.5927205  0.34753994 0.86772023 0.94484466 0.20659625 0.62953443]]
[[0.62717198 0.9767459  0.33733423]
 [0.27199963 0.74917611 0.30619961]
 [0.63100014 0.15593883 0.50771736]
 [0.87758114 0.722176   0.27743593]
 [0.5927205  0.34753994 0.86772023]
 [0.94484466 0.20659625 0.62953443]]
=====
(18, 1)
[[0.62717198]
 [0.9767459 ]
 [0.33733423]
 [0.27199963]
 [0.74917611]
 [0.30619961]
 [0.63100014]
 [0.15593883]
 [0.50771736]
 [0.87758114]
 [0.722176  ]
 [0.27743593]
 [0.5927205 ]
 [0.34753994]
 [0.86772023]
 [0.94484466]
 [0.20659625]
 [0.62953443]]


In [16]:
print(mat1.reshape(2, 9).shape)
print(mat1.reshape(9, 2))

(2, 9)
[[0.62717198 0.9767459 ]
 [0.33733423 0.27199963]
 [0.74917611 0.30619961]
 [0.63100014 0.15593883]
 [0.50771736 0.87758114]
 [0.722176   0.27743593]
 [0.5927205  0.34753994]
 [0.86772023 0.94484466]
 [0.20659625 0.62953443]]


In [17]:
# Error - 행과 열의 크기와 element의 수가 다름
mat1.reshape(2,5)

ValueError: ignored

In [18]:
# tensor 형태로 나타내기
# 1차원: vector, 2차원: matrix, 3차원: tensor
print(mat1.reshape(3,2,3).shape)
print(mat1.reshape(3,2,3))

(3, 2, 3)
[[[0.62717198 0.9767459  0.33733423]
  [0.27199963 0.74917611 0.30619961]]

 [[0.63100014 0.15593883 0.50771736]
  [0.87758114 0.722176   0.27743593]]

 [[0.5927205  0.34753994 0.86772023]
  [0.94484466 0.20659625 0.62953443]]]


### matrix 또는 tensor 형태에서도 slicing이 가능합니다!

In [19]:
mat2 = np.arange(24).reshape(-1, 4)
print(mat2)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]]


In [20]:
mat2[:1,:3]
# 2차원

array([[0, 1, 2]])

In [21]:
mat2[3, 0:2]
# 1차원 - 상수로 indexing하면 rank가 1차원 감소한다.

array([12, 13])

### Math Arithmetic Operations(사칙연산)

In [22]:
x = np.array([[1,3,5],[7,9,11],[13,15,17]])
y = np.array([[2,4,6],[8,10,12],[14,16,18]])

print(x)
print(y)

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]
[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [23]:
# add
x + y

array([[ 3,  7, 11],
       [15, 19, 23],
       [27, 31, 35]])

In [24]:
x - y

array([[-1, -1, -1],
       [-1, -1, -1],
       [-1, -1, -1]])

In [25]:
x * y

array([[  2,  12,  30],
       [ 56,  90, 132],
       [182, 240, 306]])

In [26]:
x / y

array([[0.5       , 0.75      , 0.83333333],
       [0.875     , 0.9       , 0.91666667],
       [0.92857143, 0.9375    , 0.94444444]])

In [27]:
# element당 연산 수행
print(x ** 2)
print(np.power(x, 2))

[[  1   9  25]
 [ 49  81 121]
 [169 225 289]]
[[  1   9  25]
 [ 49  81 121]
 [169 225 289]]


In [28]:
# 내적
np.dot(x, y)

array([[ 96, 114, 132],
       [240, 294, 348],
       [384, 474, 564]])

In [29]:
np.sqrt(x)

array([[1.        , 1.73205081, 2.23606798],
       [2.64575131, 3.        , 3.31662479],
       [3.60555128, 3.87298335, 4.12310563]])

In [30]:
# More on matrix operation
z1 = np.array([[2,2,2]])
z2 = np.array([[2,2]])

# Broadcasting
# 원소가 모자란 행렬은 복사되어 크기를 맞춘다
x * z1

array([[ 2,  6, 10],
       [14, 18, 22],
       [26, 30, 34]])

In [31]:
print(z2.shape)
print(x.shape)

# 단, 행이든 열이 일치해야 broadcasting이 가능하다
print(x * z2)

(1, 2)
(3, 3)


ValueError: ignored

In [32]:
# 합
print(x)
# 행끼리
print(x.sum(axis = 0))
# 열끼리
print(x.sum(axis = 1))

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]
[21 27 33]
[ 9 27 45]


In [33]:
# 평균
print(x)
print(x.mean(axis = 0))
print(x.mean(axis = 1))

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]
[ 7.  9. 11.]
[ 3.  9. 15.]


In [34]:
# 표준편차
print(x)
print(x.std(axis = 0))
print(x.std(axis = 1))

[[ 1  3  5]
 [ 7  9 11]
 [13 15 17]]
[4.89897949 4.89897949 4.89897949]
[1.63299316 1.63299316 1.63299316]


In [36]:
print(x.T)
print(z1)
print(np.dot(x, z1.T))

[[ 1  7 13]
 [ 3  9 15]
 [ 5 11 17]]
[[2 2 2]]
[[18]
 [54]
 [90]]


### Other operations

In [37]:
xx = np.random.rand(15)
print(xx)

[0.28815326 0.69361967 0.59810463 0.28165137 0.01339961 0.77894716
 0.89078736 0.54209007 0.16922    0.80419325 0.84787639 0.25152194
 0.13627897 0.45089654 0.11460316]


In [38]:
print(xx)
print(xx.argsort()) # axis를 활용해서 행렬(matrix)에도 적용할 수 있다.
xx.sort()
print(xx)

[0.28815326 0.69361967 0.59810463 0.28165137 0.01339961 0.77894716
 0.89078736 0.54209007 0.16922    0.80419325 0.84787639 0.25152194
 0.13627897 0.45089654 0.11460316]
[ 4 14 12  8 11  3  0 13  7  2  1  5  9 10  6]
[0.01339961 0.11460316 0.13627897 0.16922    0.25152194 0.28165137
 0.28815326 0.45089654 0.54209007 0.59810463 0.69361967 0.77894716
 0.80419325 0.84787639 0.89078736]


## 2. Pandas

* https://pandas.pydata.org/pandas-docs/stable/

In [39]:
import pandas as pd

### Pandas Series 만들기

* pandas series는 1차원 데이터 집합

In [40]:
pd_series = pd.Series(index = ['a','b','c','d','e'], data=[1,2,3,4,5])
pd_series

a    1
b    2
c    3
d    4
e    5
dtype: int64

In [41]:
# Pandas Series의 기초 정보
print('차원:', pd_series.ndim)
print('형태: ', pd_series.shape)
print('총 원소의 수:', pd_series.size)

print('값:', pd_series.values)
print('인덱스:', pd_series.index)

차원: 1
형태:  (5,)
총 원소의 수: 5
값: [1 2 3 4 5]
인덱스: Index(['a', 'b', 'c', 'd', 'e'], dtype='object')


### index를 활용한 데이터 탐색

In [42]:
# loc(index를 활용하여 access), iloc(integer location)

print(pd_series.loc['a'])
print(pd_series.iloc[0])

print(pd_series.loc[['a','c']])
print(pd_series.iloc[[0,2]])

1
1
a    1
c    3
dtype: int64
a    1
c    3
dtype: int64


### 데이터 삭제

In [43]:
pd_series.drop('b')

a    1
c    3
d    4
e    5
dtype: int64

In [44]:
print(pd_series)
# drop이 실제 pd_series에 반영
pd_series.drop('b', inplace=True)
print(pd_series)

a    1
b    2
c    3
d    4
e    5
dtype: int64
a    1
c    3
d    4
e    5
dtype: int64


### Pandas Dataframe 만들기

* 2차원 데이터 집합. 행렬과 비슷하게 row와 column을 갖고 있다

In [46]:
data = {
    'A': np.arange(15),
    'B': np.random.randint(low=0, high=15, size=(15)),
    'C': np.random.rand(15)
}

data_df = pd.DataFrame(data)
data_df

A   B         C
0    0   7  0.390481
1    1   4  0.795917
2    2   5  0.256229
3    3   1  0.372085
4    4   2  0.228206
5    5   2  0.607895
6    6   2  0.686304
7    7   9  0.910896
8    8   2  0.191052
9    9  12  0.021909
10  10   5  0.236311
11  11   6  0.180494
12  12   0  0.281068
13  13  14  0.662790
14  14  11  0.576175

In [48]:
data_df.head(7)

A  B         C
0  0  7  0.390481
1  1  4  0.795917
2  2  5  0.256229
3  3  1  0.372085
4  4  2  0.228206
5  5  2  0.607895
6  6  2  0.686304

In [49]:
data_df.tail(7)

A   B         C
8    8   2  0.191052
9    9  12  0.021909
10  10   5  0.236311
11  11   6  0.180494
12  12   0  0.281068
13  13  14  0.662790
14  14  11  0.576175

In [50]:
data_df.shape

(15, 3)

### Indexing and Slicing

In [51]:
data_df[1:3]

A  B         C
1  1  4  0.795917
2  2  5  0.256229

In [52]:
# 전체 index가 object index보다 우선된다
data_df.loc[1]

A    1.000000
B    4.000000
C    0.795917
Name: 1, dtype: float64

In [54]:
data_df.loc[1]['C']

0.795917015766102

In [56]:
data_df.iloc[1][2]

0.795917015766102

In [57]:
data_df.loc[1][['B', 'C']]

B    4.000000
C    0.795917
Name: 1, dtype: float64

### Add, Remove and etc

In [58]:
data_df['D'] = data_df['A'] >= 5
data_df

A   B         C      D
0    0   7  0.390481  False
1    1   4  0.795917  False
2    2   5  0.256229  False
3    3   1  0.372085  False
4    4   2  0.228206  False
5    5   2  0.607895   True
6    6   2  0.686304   True
7    7   9  0.910896   True
8    8   2  0.191052   True
9    9  12  0.021909   True
10  10   5  0.236311   True
11  11   6  0.180494   True
12  12   0  0.281068   True
13  13  14  0.662790   True
14  14  11  0.576175   True

In [59]:
data_df.drop('D', axis=1, inplace=True)

In [60]:
data_df

A   B         C
0    0   7  0.390481
1    1   4  0.795917
2    2   5  0.256229
3    3   1  0.372085
4    4   2  0.228206
5    5   2  0.607895
6    6   2  0.686304
7    7   9  0.910896
8    8   2  0.191052
9    9  12  0.021909
10  10   5  0.236311
11  11   6  0.180494
12  12   0  0.281068
13  13  14  0.662790
14  14  11  0.576175

In [61]:
data_df.sort_index(axis=0, ascending=False)

A   B         C
14  14  11  0.576175
13  13  14  0.662790
12  12   0  0.281068
11  11   6  0.180494
10  10   5  0.236311
9    9  12  0.021909
8    8   2  0.191052
7    7   9  0.910896
6    6   2  0.686304
5    5   2  0.607895
4    4   2  0.228206
3    3   1  0.372085
2    2   5  0.256229
1    1   4  0.795917
0    0   7  0.390481