<a href="https://colab.research.google.com/github/KwonTaekhyun/Python-Practice/blob/main/PyTorch_%EA%B8%B0%EC%B4%88.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Pytorch Basics

- Stevens, Antiga and Viehmann (2020), "Deep Learning with PyTorch" 참고
- PyTorch tutorial website 참고(https://tutorials.pytorch.kr/beginner/deep_learning_60min_blitz.html)

### **PyTorch**
* provides multidimensional arrays -> Tensor
* *tensors*, and an extensive *library of operations* on them

In [2]:
!pip list
# Deep learning에서 PyTorch version에 따라서 에러나 arguments가 다를 수 있다.

Package                       Version
----------------------------- ----------------------------
absl-py                       1.2.0
aeppl                         0.0.33
aesara                        2.7.9
aiohttp                       3.8.1
aiosignal                     1.2.0
alabaster                     0.7.12
albumentations                1.2.1
altair                        4.2.0
appdirs                       1.4.4
arviz                         0.12.1
astor                         0.8.1
astropy                       4.3.1
astunparse                    1.6.3
async-timeout                 4.0.2
asynctest                     0.13.0
atari-py                      0.2.9
atomicwrites                  1.4.1
attrs                         22.1.0
audioread                     3.0.0
autograd                      1.4
Babel                         2.10.3
backcall                      0.2.0
beautifulsoup4                4.6.3
bleach                        5.0.1
blis                          0.7.8

In [3]:
# torch가 설치되어 있지 않다면
# https://pytorch.org 에서 환경에 맞는 command로 설치하거나
# !pip install torch
# 또는 !pip3 install torch (Python3 환경임을 명시)

import torch

### 1. Tensor란? Tensor 만들기

* Tensors: Multidimensional arrays


In [4]:
# Create a torch.Tensor object with the given data.  It is a 1D vector
V_data = [1., 2., 3.]
V = torch.Tensor(V_data)
print(V)

# Creates a matrix
M_data = [[1., 2., 3.], [4., 5., 6]]
M = torch.Tensor(M_data)
print(M)

# Create a 3D tensor of size 2x2x2.
T_data = [[[1.,2.], [3.,4.]],
          [[5.,6.], [7.,8.]]]
T = torch.Tensor(T_data)
print(T)

tensor([1., 2., 3.])
tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[[1., 2.],
         [3., 4.]],

        [[5., 6.],
         [7., 8.]]])


In [5]:
# torch.ones: tensor를 size에 맞게 1로 채운다
a = torch.ones(3)
print(a)

b = torch.ones(2, 3)
print(b)

tensor([1., 1., 1.])
tensor([[1., 1., 1.],
        [1., 1., 1.]])


In [6]:
# torch.zeros: tensor를 size에 맞게 0으로 채운다
c = torch.zeros(4)
print(c)

d = torch.zeros(5, 2, 3)
print(d)

tensor([0., 0., 0., 0.])
tensor([[[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]],

        [[0., 0., 0.],
         [0., 0., 0.]]])


In [7]:
# 초기화하면서 현재 메모리에 존재하는 값
x = torch.empty(5, 3)
print(x)

x = torch.rand(5, 3)
print(x)

tensor([[8.1842e-35, 0.0000e+00, 3.3631e-44],
        [0.0000e+00,        nan, 0.0000e+00],
        [1.1578e+27, 1.1362e+30, 7.1547e+22],
        [4.5828e+30, 1.2121e+04, 7.1846e+22],
        [9.2198e-39, 7.0374e+22, 0.0000e+00]])
tensor([[0.6716, 0.4070, 0.5888],
        [0.6045, 0.5901, 0.4424],
        [0.8106, 0.8402, 0.5082],
        [0.7239, 0.1599, 0.9257],
        [0.1099, 0.0765, 0.3519]])


In [8]:
# torch.rand: 랜덤 숫자로 tensor를 채운다
rand_points = torch.rand(4, dtype=torch.double)
print(rand_points)

rand_points_2 = torch.rand(2, 3, dtype=torch.float)
print(rand_points_2)

tensor([0.8425, 0.3293, 0.0431, 0.9464], dtype=torch.float64)
tensor([[0.4337, 0.8476, 0.8706],
        [0.6837, 0.4029, 0.6058]])


In [9]:
# 행렬 사이즈
print(rand_points_2.size())

torch.Size([2, 3])


### 2. Indexing Tensors

In [10]:
temp = torch.Tensor([0, 1, 2, 3, 4, 5, 6, 7])

print(temp[:]) # tensor element 전체
print(temp[1:4]) # index 1과 4 사이의 원소들 출력
print(temp[1:]) # index 1부터의 원소들 출력
print(temp[:4]) # index 4까지의 원소들 출력
print(temp[-1]) # 뒤에서 첫번째 원소 출력
print(temp[:-1]) # index -1 = 뒤에서부터 index 1에 해당하는 원소까지만 출력
print(temp[1:6:2]) # index 1과 6 사이의 원소 출력, 이때 2개 단위로 건너뛰면서

tensor([0., 1., 2., 3., 4., 5., 6., 7.])
tensor([1., 2., 3.])
tensor([1., 2., 3., 4., 5., 6., 7.])
tensor([0., 1., 2., 3.])
tensor(7.)
tensor([0., 1., 2., 3., 4., 5., 6.])
tensor([1., 3., 5.])


In [11]:
temp2 = torch.Tensor([[1, 2, 3], [4, 5, 6]])

print(temp2)
print(temp2[1:])
print(temp2[1:, 1:])
print(temp2[1:, 0])

tensor([[1., 2., 3.],
        [4., 5., 6.]])
tensor([[4., 5., 6.]])
tensor([[5., 6.]])
tensor([4.])


## 3. Tensor element types

add 'dtype' argument to tensor constructors 

-> specify the data type that will be contained in the tensor

dtype을 구성하는 것:
- possible values the tensor can hold (int, float, ...)
- number of bytes per value (8, 16, 32, ...)

예)

- torch.float32 (= torch.float): 32-bit floating point

- torch.float64 (= torch.double): 64-bit, double-precision floating point

- torch.float16 (= torch.half): 16-bit, half-precision floating point

- torch.int32 (= torch.int): 32-bit integers

- torch.int64 (= torch.long): 64-bit integers

- torch.bool: Boolean

...



In [12]:
float_points = torch.ones(5, 2, dtype=torch.float32)
int_points = torch.zeros(3, dtype=torch.int64)

print(float_points)
print(int_points)

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([0, 0, 0])


In [13]:
# default: float
default_points = torch.Tensor([2, 2])
print(default_points)

tensor([2., 2.])


In [14]:
# find out dtype
print(float_points.dtype)
print(int_points.dtype)
print(default_points.dtype)

torch.float32
torch.int64
torch.float32


In [15]:
# other forms of specifying dtype

to_int_1 = float_points.int()
print(to_int_1.dtype)

# 'to' checks whether the conversion is necessary and if so, does it.
to_int_2 = float_points.to(torch.int64)
print(to_int_2.dtype)

to_float_1 = int_points.float()
print(to_float_1.dtype)

to_float_2 = int_points.to(dtype=torch.float16)
print(to_float_2.dtype)


torch.int32
torch.int64
torch.float32
torch.float16


## 4. The Tensor API

tensor와 관련된 대부분의 operation은 torch 모듈에 구현되어 있음

예)

- math operations: abs, cos, mean, std, norm, equal, max, ...
- tensor element-wise sum, concat, ...
- random sampling: randn, normal, ...

online docs: https://pytorch.org/docs


## 5. Tensor Shape and Reshape


In [16]:
# shape: Returns the size of the tensor

a = torch.Tensor([[1, 2, 3], [4, 5, 6]])

print(a)
print(a.shape)


tensor([[1., 2., 3.],
        [4., 5., 6.]])
torch.Size([2, 3])


In [17]:
# size()

print(a.size())

torch.Size([2, 3])


In [18]:
# Reshape: 주어진 shape로 original tensor에서 데이터를 가져와서 reshape한다

a_reshape = a.reshape(3, 2)
print(a_reshape)
print(a_reshape.shape)

a_reshape_2 = a.reshape(-1, 2) # the size -1 is inferred from other dimensions
print(a_reshape_2)
print(a_reshape_2.shape)

tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
torch.Size([3, 2])
tensor([[1., 2.],
        [3., 4.],
        [5., 6.]])
torch.Size([3, 2])


In [19]:
# if shape is not compatible with the current shape:
a_no_reshape = a.reshape(4, 2)

RuntimeError: ignored

In [20]:
# View: Returns a new tensor with the same data as the original tensor but of a different shape.
# reshape과 거의 비슷하게 사용

x = torch.randn(4, 4)
print(x.size())

y = x.view(16)
print(y.size())

z = x.view(-1, 8)  # the size -1 is inferred from other dimensions
print(z.size())

torch.Size([4, 4])
torch.Size([16])
torch.Size([2, 8])


## 6. Transpose

In [22]:
# torch.t: 가장 간단한 형태의 transpose
# Expects input to be <= 2-D tensor and transposes dimensions 0 and 1.
# 0-D and 1-D tensors are returned as is. When input is a 2-D tensor this is equivalent to transpose(input, 0, 1).

x = torch.randn(1)
print(x)
print(torch.t(x))

y = torch.randn(3)
print(y)
print(torch.t(y))

z = torch.randn(2, 3)
print(z)
print(torch.t(z))

tensor([-0.8704])
tensor([-0.8704])
tensor([ 1.1973,  0.7078, -0.1636])
tensor([ 1.1973,  0.7078, -0.1636])
tensor([[-0.3121, -1.7858, -0.9087],
        [-2.0189, -1.7410,  0.5253]])
tensor([[-0.3121, -2.0189],
        [-1.7858, -1.7410],
        [-0.9087,  0.5253]])


In [23]:
# torch.transpose
# Returns a tensor that is a transposed version of input. The given dimensions dim0 and dim1 are swapped.

w = torch.randn(2, 3)
print(w)
print(torch.transpose(w, 0, 1))

tensor([[-0.8484, -0.1848, -1.0985],
        [ 0.4142,  0.7245,  0.4809]])
tensor([[-0.8484,  0.4142],
        [-0.1848,  0.7245],
        [-1.0985,  0.4809]])


In [24]:
# more complex case

real_example = torch.randn(64, 128, 768)
print(real_example.shape)
transposed = torch.transpose(real_example, 1, 2)
print(transposed.shape)

torch.Size([64, 128, 768])
torch.Size([64, 768, 128])


## 7. Operations Example

In [25]:
x = torch.ones(1, 2)
print(x)
y = torch.ones(5, 3)
print(y)

tensor([[1., 1.]])
tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]])


In [26]:
# 적어도 행 또는 열이 같아야 한다!
print(x+y)

RuntimeError: ignored

In [28]:
y = torch.ones(5, 2)
print(y)

# Tensor는 np와 달리 미리 공간이 잡혀있다고 생각하면 좋다!

# 1.
print(x+y)
# 2. 
print(torch.add(x, y))
# 3.
result = torch.empty(5, 2)
torch.add(x, y, out=result)
print(result)
# 4. inplace
print(y.add_(x))

tensor([[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]])
tensor([[2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.]])
tensor([[2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.],
        [2., 2.]])


### Additional Information
- torch 연산(transpose, indexing, slicing, mathematical operations, linear algebra 등)은 아래 링크에서 추가로 확인 가능
- https://pytorch.org/docs/stable/torch.html

### Reference: Moving tensors to the GPU

if you are using Google Colaboratory, please set the runtime type to GPUs.

화면 상단 **런타임 >> 런타임 유형 변경 >> 하드웨어 가속기 GPU 선택**


In [29]:
torch.cuda.is_available()

True

In [30]:
import torch # 런타임 유형을 변경하면 colab 세션이 초기화될 수 있음

points_gpu = torch.tensor([[4.0, 1.0], [5.0, 3.0], [2.0, 1.0]], device='cuda')

print(points_gpu)

tensor([[4., 1.],
        [5., 3.],
        [2., 1.]], device='cuda:0')


In [31]:
points = torch.randn(2, 3)
points_gpu = points.to(device='cuda')

print(points_gpu)

tensor([[ 0.7789,  0.5335,  0.0031],
        [-0.8024, -0.8180, -0.8044]], device='cuda:0')


If our machine has more than one GPU, we can also decide on which GPU we allocate the tensor by passing a zero-based integer identifying the GPU on the machine, such as cuda:0, cuda:1, ...

In [ ]:
points_gpu_0 = points.to(device='cuda:0')
print(points_gpu_0)

In [ ]:
# operations performed on CPU and GPU

points = 2 * points   # cpu에서 계산 수행
print(points)

points_op_gpu = 2 * points.to(device='cuda')  # gpu에서 계산 수행
print(points_op_gpu)

In [ ]:
# move the tensor back to the CPU

points_cpu = points_gpu_0.to(device='cpu')
print(points_cpu)
print(points_cpu.device)

In [ ]:
# shorter forms
points_gpu = points.cuda()
print(points_gpu)

points_gpu = points.cuda(0)
print(points_gpu)

points_cpu = points_gpu.cpu()
print(points_cpu)

## 8. Numpy Interpretability

PyTorch tensors can be converted to NumPy arrays and vice versa very efficiently.

In [33]:
# tensor to numpy array

points = torch.ones(3, 4)
points_np = points.numpy()

print(points_np)
type(points_np)

[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]


numpy.ndarray

In [34]:
# numpy arrray to tensor

points = torch.from_numpy(points_np)

print(points)
type(points)

tensor([[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]])


torch.Tensor

## 9. Save and load tensors

save tensors to a file and load them back at some point

PyTorch uses pickle under the hood to serialize the tensor object, plus dedicated serialization code for the storage.

In [ ]:
print(points)

torch.save(points, './points_temp.t')

In [ ]:
load_points = torch.load('./points_temp.t')
print(load_points)